name: weather_project
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 网络请求框架
  dio: ^2.1.5
  # 数据加密框架
  encrypt: ^3.1.0
  #json数据转换框架
  json_annotation: ^2.0.0
  #日期转换框架
  intl: ^0.15.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #权限申请框架
  permission_handler: ^3.1.0
  #数据库操作框架
  sqflite: ^1.1.5
  #高德地图定位
  amap_location: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json数据转换框架
  build_runner: ^1.0.0
  json_serializable: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - icons/icon_blustery.png
    - icons/icon_cloudy.png
    - icons/icon_cold.png
    - icons/icon_dust.png
    - icons/icon_duststorm.png
    - icons/icon_foggy.png
    - icons/icon_haze.png
    - icons/icon_heavy_rain.png
    - icons/icon_heavy_snow.png
    - icons/icon_heavy_storm.png
    - icons/icon_hot.png
    - icons/icon_hurricane.png
    - icons/icon_ice_rain.png
    - icons/icon_light_rain.png
    - icons/icon_light_snow.png
    - icons/icon_moderate_rain.png
    - icons/icon_moderate_snow.png
    - icons/icon_mostly_cloudy_day.png
    - icons/icon_mostly_cloudy_night.png
    - icons/icon_overcast.png
    - icons/icon_partly_cloudy_day.png
    - icons/icon_partly_cloudy_night.png
    - icons/icon_sand.png
    - icons/icon_sandstorm.png
    - icons/icon_severe_storm.png
    - icons/icon_shower.png
    - icons/icon_sleet.png
    - icons/icon_snow_flurry.png
    - icons/icon_snowstorm.png
    - icons/icon_storm.png
    - icons/icon_sunny_day.png
    - icons/icon_sunny_night.png
    - icons/icon_thundershower.png
    - icons/icon_thundershower_with_hail.png
    - icons/icon_tornado.png
    - icons/icon_tropical_storm.png
    - icons/icon_unknown.png
    - icons/icon_windy.png
    - icons/icon_humidity.png
    
    - icons/2.0x/icon_blustery.png
    - icons/2.0x/icon_cloudy.png
    - icons/2.0x/icon_cold.png
    - icons/2.0x/icon_dust.png
    - icons/2.0x/icon_duststorm.png
    - icons/2.0x/icon_foggy.png
    - icons/2.0x/icon_haze.png
    - icons/2.0x/icon_heavy_rain.png
    - icons/2.0x/icon_heavy_snow.png
    - icons/2.0x/icon_heavy_storm.png
    - icons/2.0x/icon_hot.png
    - icons/2.0x/icon_hurricane.png
    - icons/2.0x/icon_ice_rain.png
    - icons/2.0x/icon_light_rain.png
    - icons/2.0x/icon_light_snow.png
    - icons/2.0x/icon_moderate_rain.png
    - icons/2.0x/icon_moderate_snow.png
    - icons/2.0x/icon_mostly_cloudy_day.png
    - icons/2.0x/icon_mostly_cloudy_night.png
    - icons/2.0x/icon_overcast.png
    - icons/2.0x/icon_partly_cloudy_day.png
    - icons/2.0x/icon_partly_cloudy_night.png
    - icons/2.0x/icon_sand.png
    - icons/2.0x/icon_sandstorm.png
    - icons/2.0x/icon_severe_storm.png
    - icons/2.0x/icon_shower.png
    - icons/2.0x/icon_sleet.png
    - icons/2.0x/icon_snow_flurry.png
    - icons/2.0x/icon_snowstorm.png
    - icons/2.0x/icon_storm.png
    - icons/2.0x/icon_sunny_day.png
    - icons/2.0x/icon_sunny_night.png
    - icons/2.0x/icon_thundershower.png
    - icons/2.0x/icon_thundershower_with_hail.png
    - icons/2.0x/icon_tornado.png
    - icons/2.0x/icon_tropical_storm.png
    - icons/2.0x/icon_unknown.png
    - icons/2.0x/icon_windy.png
    - icons/2.0x/icon_humidity.png

    


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
